### ISSUE TITLE
Create a Dockerfile for deploying it

### ISSUE THREAD

**Issue by camilosampedro** [hashrocket/hr-til#127]
(This is not a bug so I skipped the template)

I was giving a look to your work, seeing it is a very interesting and short way to pubish a post as a group or company. I was just thinking that it would be very nice to have a __Dockerfile__ (Or something in Kubernetes) to easily deploy an instance of `hr-til`, even for improving your deploy pipeline. 

As I see in the `README.md` instructions it has very short install steps, it might not be a very complex docker container. :smile: 

Thanks in advance!

**Comment by jwworth** [comment]
Glad you like the project, and thanks for submitting this idea!

The reason we don't have a Dockerfile or equivalent is because we deploy to Heroku. Without regularly deploying a Docker container to production, we would have no way to ensure that the Dockerfile works, or continues to work in the future.

**Comment by camilosampedro** [comment]
I see your point.

Currently you [can deploy to Heroku with Docker](https://devcenter.heroku.com/articles/container-registry-and-runtime#using-a-ci-cd-platform), but I understand that the current workflow with Heroku is working. Docker can be an alternative that you can consider at some point in the future.

Thank you!
