### ISSUE TITLE
Plans for customizing TIL?

### ISSUE THREAD

**Issue by clemensp** [hashrocket/hr-til#17]
Hello,

I'm trying to launch TIL for my company's engineering team, and we have some questions regarding customizations.

Currently, TIL is a Rails app.  This means that we have to clone the repo and make changes to the code to customize styles and templates.

What are you guys' plan to support customization?
For example, do you plan to turn TIL into an engine, so that I can load it as a gem and provide my own stylesheets?

Cheers!

**Comment by hashrocketeer** [comment]
Interesting idea. No, at the moment we have open-sourced this site to expose some of our development and design practices, allow people to borrow ideas or the entire app for themselves, and contribute if they wish.

Creating something that portable is beyond our current aspirations. If people encounter features of the code that make that difficult, we'd be willing to consider making changes so the application can be more generalized.

**Comment by jwworth** [comment]
Interesting idea. No, at the moment we have open-sourced this site to expose some of our development and design practices, allow people to borrow ideas or the entire app for themselves, and contribute if they wish.

Creating something that portable is beyond our current aspirations. If people encounter features of the code that make that difficult, we'd be willing to consider making changes so the application can be more generalized.

**Comment by clemensp** [comment]
Just to be clear, my intention was to see if there's a direction you wanted to take the project in, so that I can contribute in a way that aligns with your thoughts.  I am definitely not asking you guys to add features or make any changes.  :smiley: 

If I were to explore turning TIL into an engine, is that something you guys would be interested in?
Otherwise, my path of least resistance for customizing it would be to fork and modify.  I imagine that there will be less opportunities to contribute back to this project with the fork and modify approach.

Any thoughts?

Also, I should mention that I'm very thankful that you've open sourced this project. :+1:
Discovering the slack integration was a pleasant surprise, as that would have been one of the first things I added!

**Comment by jwworth** [comment]
Thanks for the feedback; we really appreciate it!

We have been mulling this idea over for a few days. At the moment, the maintenance overhead of separate repositories and the added abstraction of an engine seem larger than the conveniences it may provide. I want to keep this issue open for other thoughts, but at the moment I don't think that's a road we want go down.

If I was cloning this application, I would see a handful of obstacles to customizing it. I'd want to change the seed data so my channels were not Ember, Vim, and Elixir (the ones we chose for Hashrocket). I'd want to change the page title, header, and footer, and I'd want to customize the stylesheets. All of these could be changed on a fork, or abstracted into environmental variables or separate stylesheets that are optionally required, and submitted back as a pull request. That would be an great addition because it would help generalize the app.

If you'd like to try converting the project to an engine, feel free, but right now we'd be more receptive to keeping this a standalone Rails application.

**Comment by jwworth** [comment]
This is a cool idea. Outside of our plans right now, so closing the issue. Feel free to reopen.
