### ISSUE TITLE
Getting error during rake db:setup

### ISSUE THREAD

**Issue by inexion** [hashrocket/hr-til#21]
Can't seem to create 'Developer #1'...

`*** Loading development seed data
Creating developer #1
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Email is invalid
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/validations.rb:79:in `raise_record_invalid'`

The contents of `config/seeds/development.rb`:

`5.times do |i|
  puts "Creating developer ##{i + 1}"
  username = Phil.name.downcase.delete(' ')
  Developer.create!(username: username, email: "#{username}@hashrocket.com")
end`

Anything I can do to get this moving?

**Comment by jwworth** [comment]
This is failing on the `db:seed` step of `db:setup`. Have you tried copying `config/application.yml.example` as `config/example.yml`? There was a typo in the README explanation of how to do that until this morning:

https://github.com/hashrocket/hr-til/commit/c3058a7bbecd00119bd5b1c2c46114fc6496eefb

**Comment by inexion** [comment]
I had recently tried this (about an hour ago, but I can try again) - I just removed the 'format' bit from email validation...

`format: { with: Proc.new { /\A.+@(#{ENV['permitted_domains']})\z/ } }` 

And it went through just fine.

This isn't a solution of course, but I wanted to get it working. I will try again.

**Comment by jwworth** [comment]
That validation looks for an environmental variable called `permitted_domains` that is set in `config/application.yml.example` and your copied `config/application.yml`. It's a string that represents which domain email addresses (i.e. `gmail.com`, `hashrocket.com`) are allowed to log into the application.

Removing the validation will allow the seeds to run, but this validation was necessary in production because Google Omniauth doesn't seem to restrict domains exactly as described in their documentation. We needed it to validate it on our end, too.

If you don't want to restrict the domain beyond a valid Google email address, then removing the validation is okay. If you do, set that variable to your domain of choice.

As an aside, we should probably change our development environmental variables and seeds to `example.com` to make this application more generic.

**Comment by jwworth** [comment]
Closing this issue, because it is related to a missing environmental variable that is now in `config/application.yml.example`, and setup is explained in the README.
